version: "3.3"
services:
  mopidy:
    profiles:
      - dev
      - prod
    image: pvincent4/mopidy:latest
    build:
      context: ./mopidy
      dockerfile: Dockerfile
    ports:
      - ${PORT_MOPIDY}:6680 #Mopidy
      - ${PORT_MPD}:6600 #MPD server and control
    env_file:
      - .env
    volumes:
      - ./data/music:/app/Music
      - ./tmp/snapserver:/tmp
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  o2m:
    profiles:
    # - dev
      - prod
    image: pvincent4/o2m:latest
    build:
      context: ./o2m
      dockerfile: Dockerfile
    ports:
      - ${PORT_O2M_API}:6681
    depends_on: 
      - mopidy
      - mysql
    volumes:
      - ./o2m:/app
    restart: always
    env_file:
      - .env

  snapserver:
    profiles:
      - dev
      - prod
    image: jaedb/snapserver
    ports:
      - ${PORT_SNAPSERVER_1}:1704
      - ${PORT_SNAPSERVER_2}:1705
      - ${PORT_SNAPSERVER_HTTP}:1780
    volumes:
      - ./tmp/snapserver:/tmp
      - ./snapserver/snapserver.conf:/etc/snapserver.conf
      #- ./docker/snapserver/snapserver.json:/root/.config/snapserver/server.json
    depends_on: 
      - mopidy

  back:
    profiles:
      - dev
    #  - prod
    build: backend/
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_migrations/:/pb_migrations
      - ./backend/pb_data/:/pb_data/
  front:
    profiles:
      - dev
    # - prod
    build: frontend/
    volumes:
      - ./frontend/src/:/app/src
    network_mode: host
    env_file:
      - .env

  mysql:
    profiles:
    #  - dev
      - prod
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: o2m
      MYSQL_USER: o2m
      MYSQL_PASSWORD: o2m
    ports:
      - "${PORT_MYSQL}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./o2m/samples/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    profiles:
    #  - dev
      - prod
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      #PMA_USER: xxx
      #PMA_PASSWORD: xxx
    ports:
      - "${PORT_PHPMYADMIN}:80"
    depends_on:
      - mysql
